# Generated by Django 4.0.2 on 2022-03-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcafeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('contactNumber', models.IntegerField(verbose_name=15)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
