# Generated by Django 4.0.2 on 2022-03-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcafeApp', '0002_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
