# Generated by Django 4.0.2 on 2022-03-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcafeApp', '0003_alter_enquiry_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='contactNumber',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
