# Generated by Django 4.0.2 on 2022-03-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcafeApp', '0004_remove_enquiry_contactnumber_enquiry_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
