# Generated by Django 4.0.2 on 2022-03-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcafeApp', '0005_alter_enquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
